name: agihouse 
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - python=3.9.13
  - pip=23.3.1
  - pandas=2.1.4
  - scikit-learn=1.2.2
  - pip:
    - pytdc==1.1.0
    - ai21==2.15.0